### ISSUE TITLE
[rbac-manager] Make securityContext for pod and container configurable

### ISSUE THREAD

**Issue by manzsolutions-lpr** [reactiveops/charts#1006]
**Is your feature request related to a problem? Please describe.**
Using the [Pod Security Standard "restricted" level](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted) requires certain securityContext settings to be set. While the container of rbac-manager actually already fulfills most of the requirements (uid has to be explicitly set if the container image uses a named user) the mandatory seccompProfile is missing and since the securityContext for neither pod nor container is configurable this cannot be amended trivially.

**Describe the solution you'd like**
Ideally the current values of the container's `securityContext` would be moved to values.yaml and additionally `podSecurityContext` be made available via values.yaml, too. This would mirror the behaviour of default charts created by `helm create <chart name>` and be fully backwards compatible.

**Describe alternatives you've considered**
One could probably use kustomize to modify the deployment post-rendering. Since PSS/PSA are default features it will likely be desirable to have a more straightforward solution though.

**Additional context**
N/A

**Comment by sudermanjr** [comment]
The proposed solution here seems very reasonable. Thanks for bringing this to our attention!

Is this something you would be willing to open a PR for?
