### ISSUE TITLE
Goldilocks Ingress is not working ,getting 404 

### ISSUE THREAD

**Issue by subhranil05** [reactiveops/charts#1074]
I'm using the stable helm chart for goldilocks with ingress enabled, but it is not reaching to dashboard, throwing 404.
Below is my ingress yaml. Please guide .

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    konghq.com/https-redirect-status-code: "308"
    konghq.com/protocols: https
    konghq.com/strip-path: "false"
    meta.helm.sh/release-name: goldilocks
    meta.helm.sh/release-namespace: goldilocks
  generation: 1
  labels:
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/instance: goldilocks
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: goldilocks
    helm.sh/chart: goldilocks-6.4.0
  name: goldilocks-dashboard
  namespace: goldilocks
spec:
  ingressClassName: kong
  rules:
  - host: fluxxx-xxxx.xxxx.xxx
    http:
      paths:
      - backend:
          service:
            name: goldilocks-dashboard
            port:
              name: http
        path: /goldilocks
        pathType: ImplementationSpecific

**Comment by sudermanjr** [comment]
Unfortunately we're not really experts on Kong ingress objects. A 404 coming from your ingress controller generally indicates an issue with the configuration of the ingress related to the ingress controller, not Goldilocks itself.

Posting properly indented YAML of the ingress, along with the output of `kubectl describe ingress` would be helpful in diagnosing any potential issues.

**Comment by subhranil05** [comment]
@sudermanjr here it is
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    konghq.com/https-redirect-status-code: "308"
    konghq.com/protocols: https
    konghq.com/strip-path: "false"
    meta.helm.sh/release-name: goldilocks
    meta.helm.sh/release-namespace: goldilocks
  creationTimestamp: "2023-01-31T15:13:47Z"
  generation: 1
  labels:
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/instance: goldilocks
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: goldilocks
    helm.sh/chart: goldilocks-6.4.0
  name: goldilocks-dashboard
  namespace: goldilocks
  resourceVersion: "1070903"
  uid: aa9727b0-66eb-4a27-9911-410e5562ede0
spec:
  ingressClassName: kong
  rules:
  - host: fluxxx-xxxxx.xxxx.xxx
    http:
      paths:
      - backend:
          service:
            name: goldilocks-dashboard
            port:
              name: http
        path: /goldilocks
        pathType: ImplementationSpecific
        
        Output:
        
 $ k describe ing goldilocks-dashboard -n goldilocks
Name:             goldilocks-dashboard
Labels:           app.kubernetes.io/component=dashboard
                  app.kubernetes.io/instance=goldilocks
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=goldilocks
                  helm.sh/chart=goldilocks-6.4.0
Namespace:        goldilocks
Address:          20.219.43.46
Ingress Class:    kong
Default backend:  <default>
Rules:
  Host                       Path  Backends
  ----                       ----  --------
  fluxxx-xxxxx.xxxx.xxx  
                             /goldilocks   goldilocks-dashboard:http (10.xxx.xx.xx2:8080,10.xxx.xx.x1:8080)
Annotations:                 konghq.com/https-redirect-status-code: 308
                             konghq.com/protocols: https
                             konghq.com/strip-path: false
                             meta.helm.sh/release-name: goldilocks
                             meta.helm.sh/release-namespace: goldilocks
Events:                      <none>

**Comment by sudermanjr** [comment]
It's hard to tell what I'm seeing without indentation, but it does look at least like the goldilocks service has endpoints in your cluster, and that the ingress is pointed at it. 

I would recommend checking the logs in your kong ingress controller.

**Comment by murali-krishna** [comment]
@subhranil05 Can you change the path in your ingress.yaml from `/goldilocks` to `/`? There's no /goldilocks page in dashboard which is why you are seeing 404
