### ISSUE TITLE
vpa still using k8s.gcr.io

### ISSUE THREAD

**Issue by neiser** [reactiveops/charts#1083]
### What happened?

The docker image for vpa [is still hosted at `k8s.gcr.io`](https://github.com/FairwindsOps/charts/blob/master/stable/vpa/values.yaml#L43), which is going to be sunsetted in April 2023, according to [this blog post](https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/).

I'm not sure if this is a bug here [or upstream](https://github.com/kubernetes/autoscaler), as I couldn't figure out who exactly is responsible for pushing that image.

### What did you expect to happen?

Helm chart uses image from `registry.k8s.io`.

### How can we reproduce this?

See above.

### Version

vpa-1.6.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment]
This would be the responsibility of the folks over at kubernetes/autoscaler. We simply provide the chart as a convenience for working with Goldilocks.

Once they've made the change, we will need to modify the chart, but we are dependent on them.

**Comment by neiser** [comment]
@sudermanjr Thanks for your quick response. I'll open an issue there and reopen this one once they made their homework :smile: 

Upstream issue: https://github.com/kubernetes/autoscaler/issues/5486

**Comment by bo0tzz** [comment]
It seems like [this has been solved upstream](https://github.com/kubernetes/autoscaler/issues/5491), can this issue be reopened?

**Comment by neiser** [comment]
@bo0tzz Re-opened it, I hope that's ok @sudermanjr

**Comment by roee-landesman** [comment]
Opened a fix PR https://github.com/FairwindsOps/charts/pull/1127

**Comment by sudermanjr** [comment]
This should be fixed in chart >1.7.0
