### ISSUE TITLE
`rbac-manager` Chart not applying `namespace`

### ISSUE THREAD

**Issue by demarius** [reactiveops/charts#1096]
### What happened?

Deployed Helm Chart version `1.15.2.`

### What did you expect to happen?

Expected `namespace` passed to `Helm` arguments to be respected in resulting manifests.

### How can we reproduce this?

```
helm template rbac-manager \
     --version 1.15.2 \
     --namespace rbac-manager \
     --create-namespace \
     fairwinds-stable/rbac-manager```

### Version

1.15.2

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Noted in Fairwinds Slack channel.

**Comment by sudermanjr** [comment]
I don't think the `helm template` command respects namespace, and only `helm install` does that via the kubernetes client configuration. This would be an issue or request for Helm, not for any specific chart.

If you are planning to use the output of helm template, then using `helm template | kubectl  apply --namespace` would be more appropriate.

**Comment by sudermanjr** [comment]
There is a rather lengthy discussion in the Helm repo about this: https://github.com/helm/helm/issues/3553

**Comment by demarius** [comment]
@sudermanjr thank you!

**Comment by demarius** [comment]
@sudermanjr I reviewed the issue and it seems unlikely any progress will be made. It's not necessary for me as I'm using `ytt` to edit my manifests, but it might be reasonable for Fairwinds to make use of the `Release.Namespace` parameter since there may be no upstream correction.

**Comment by sudermanjr** [comment]
It's my loosely-held opinion that we should leave this up to the end-user to manage with whatever their deployment tool of choice is, rather than modifying the chart

**Comment by demarius** [comment]
Makes sense to me, but worth noting that the `rbac-manager` documentation itself recommends installing with the above command, which does not work as expected (the documentation does not specify a version, but it implies this command will install `rbac-manager` into the `rbac-manager` namespace which it does not).
