### ISSUE TITLE
Goldilocks RBAC: enableArgoproj

### ISSUE THREAD

**Issue by rverchere** [reactiveops/charts#1109]
Hi,

When installing Goldilocks, the enableArgoproj value is set to `true` by default.

As people does not have Argo installed in their cluster, I suggest set it to `false`.

**Comment by sudermanjr** [comment]
Since this would be a non backward-compatible change to the values file, I'm not sure it's worth changing a major version of the chart for this, but I also agree that it probably shouldn't be on by default. Curious what others think
