### ISSUE TITLE
[stable/insights-agent] prometheus-server not starting on GKE

### ISSUE THREAD

**Issue by amalic** [reactiveops/charts#1158]
### What happened?

Looking into the logs I see this line
```
stream logs failed container "prometheus-server-instrumentation" in pod "prometheus-server-674dd66796-kcfhk" is waiting to start: CreateContainerConfigError for insights-agent/prometheus-server-674dd66796-kcfhk (prometheus-server-instrumentation)
```

### What did you expect to happen?

Prometheus server running without issues.

### How can we reproduce this?

Install prometheus-server add on on GKE-cluster

### Version

latest

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Seeing this event popping up, which is most likely the root cause:
```Error: container's runAsUser breaks non-root policy (pod: "prometheus-server-674dd66796-kcfhk_insights agent(f27377a3-aea9-4e47-bb94-dfae22c52317)", container: prometheus-server-instrumentation)```

**Comment by sudermanjr** [comment]
Which version of the insights-agent chart was this from? Also, can you please share your values file?

**Comment by sudermanjr** [comment]
I believe we use the https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus chart as as sub-chart as a starting point.
