### ISSUE TITLE
[stable/polaris]: Support deployment using ArgoCD 

### ISSUE THREAD

**Issue by ErikLundJensen** [reactiveops/charts#1182]
**Is your feature request related to a problem? Please describe.**
The deployment of ValidatingWebhookConfiguration and MutatingWebhookConfiguration manifests are depending upon Helm webhooks as these objects must not be created before the polaris-webhook pods are ready.

However, ArgoCD does not implement Helm webhooks directly as ArgoCD uses helm template for rendering of the chart. The configuration objects are therefore created before any of the pods starts.
Thereby it is not possible to deploy the Polaris Helm chart with enabled webhook validation using ArgoCD.

**Describe the solution you'd like**
ArgoCD implements it own webhooks which can be specified as annotations. For example:
```
annotations:
  argocd.argoproj.io/hook: PostSync
```
Adding these annotation to the ValidatingWebhookConfiguration and MutatingWebhookConfiguration manifests will instruct ArgoCD to wait for the pods to be ready.

Creating a new option `argocd: true` in the helm chart can be used for activating these annotations.

**Describe alternatives you've considered**
Alternative general solution is to add optional annotations in the ValidatingWebhookConfiguration and MutatingWebhookConfiguration manifests. This would require the users of the chart to specify the ArgoCD annotations themselves.

**Additional context**
Polaris chart version: 5.7.4
GitOps/ArgoCD

**Comment by sudermanjr** [comment]
In general I'm not a huge fan of hard-coding the way ArgoCD needs to deploy into the chart. However, I think adding the ability to add annotations is a perfectly acceptable solution and will support all users, not just argoCD users.

**Comment by ErikLundJensen** [comment]
Thanks, maybe updating some documentation would be nice as it is hard to know that you have to override those annotation when not using `helm install`.

I had hoped we could have piggybacked #1187 together with this, however, I have created a new issue instead.

**Comment by sudermanjr** [comment]
Are you referring to the Polaris documentation? That could definitely be a good addition. Would you want to open a PR for that?

**Comment by ErikLundJensen** [comment]
Yes, I'll do that.
