### ISSUE TITLE
[stable/polaris] Chart should not depend upon .Capabilities.APIVersions

### ISSUE THREAD

**Issue by ErikLundJensen** [reactiveops/charts#1187]
**Is your feature request related to a problem? Please describe.**
In a GitOps setup like ArgoCD you want to be in control of what is deployed. Using `.Capabilities.APIVersions` only reflects the version at the time of deployment. If cert-manager is upgraded then the deployed Polaris will not be updated.

Furthermore, ArgoCD does not support `.Capabilities.APIVersions.Has` for `cert-manager.io` APIs.

**Describe the solution you'd like**
Add new option to overrule the cert-manager API version.
For example
```
webhook:
  certManager:
    apiVersion: "cert-manager.io/v1" 
```

and update webhook.cert.yaml to use this new field if configured.

**Describe alternatives you've considered**
Remove all requirments to use `helm install` for deployment of any of the FairwindsOps charts.

**Additional context**
GitOps, ArgoCD, less dependencies to `helm hooks`

**Comment by sudermanjr** [comment]
This would be a great addition. We already do this in a few other charts. Do you want to add it or shall I go ahead and do the PR?

**Comment by ErikLundJensen** [comment]
Please go ahead. That way it will be aligned with your other charts.
