### ISSUE TITLE
[stable/insights-agent] kube-bench does not work with k3s

### ISSUE THREAD

**Issue by azzlack** [reactiveops/charts#1197]
### What happened?

The kube-bench container fails to start, and gives the following error:

```
  Warning  FailedMount  2m25s                 kubelet            Unable to attach or mount volumes: unmounted volumes=[etc-kubernetes], unattached volumes=[tmp var-lib etc-systemd etc-kubernetes usr-bin kube-api-access-hd7hk output]: timed out waiting for the condition
  Warning  FailedMount  18s (x10 over 4m28s)  kubelet            MountVolume.SetUp failed for volume "etc-kubernetes" : hostPath type check failed: /etc/kubernetes is not a directory
```

### What did you expect to happen?

Expected the kube-bench container to run to completion

### How can we reproduce this?

Set up a k3s cluster using the following commands:

```
export K3S_TOKEN=__something__
curl -sfL https://get.k3s.io | sh -s - server --cluster-init --disable traefik
# Get ip for master node and store in K3S_MASTER_IP
curl -sfL https://get.k3s.io | sh -s - agent --server https://${K3S_MASTER_IP}:6443
curl -sfL https://get.k3s.io | sh -s - agent --server https://${K3S_MASTER_IP}:6443
```

### Version

2.18.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by azzlack** [comment]
Possibly because k3s install folder is not `/etc/kubernetes`?  
I think it installs in `/etc/rancher/k3s` or `/var/lib/rancher/k3s/server/`, but not sure

**Comment by sudermanjr** [comment]
@rbren Seems like we need to add this as a possible configuration option.

**Comment by rbren** [comment]
I don't think kube-bench plays nicely with k3s unfortunately. Relevant context here: https://github.com/aquasecurity/kube-bench/discussions/1178

k3s is so different from a typical kubernetes setup that my guess is it's out of scope for kube-bench

**Comment by rbren** [comment]
I'm going to close this as out-of-scope, since it seems to be mostly out of our control. If you do find a workaround for running kube-bench on k3s, let us know!
