### ISSUE TITLE
[stable/insights-agent] duplicate keys when kube-bench is enabled

### ISSUE THREAD

**Issue by intrand** [reactiveops/charts#1199]
### What happened?

I've enabled kube-bench and it produced duplicate keys "volumes" when I used `helm template`.

It appears to me that...
- the container spec is defined [here, where you can see volumes](https://github.com/FairwindsOps/charts/blob/master/stable/insights-agent/templates/kube-bench/_container.yaml#L8)
- the kube-bench cronjob [includes its own volumes](https://github.com/FairwindsOps/charts/blob/master/stable/insights-agent/templates/kube-bench/cronjob.yaml#L21)
- and the kube-bench cronjob also [includes the previously mentioned container spec](https://github.com/FairwindsOps/charts/blob/master/stable/insights-agent/templates/kube-bench/cronjob.yaml#L40)

### What did you expect to happen?

Declare "volumes" only once for the same pod

### How can we reproduce this?

enable kube-bench in your values.yaml and run `helm template`

### Version

HEAD

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Works with chart version 2.18.1 without issue.

**Comment by sudermanjr** [comment]
I am unable to reproduce this with 2.18.2 and just enabling kube-bench. Are there more values that need to be set? We worked on this in a few places, and I had thought we found them all. The templates are pretty complex, so just seeing volumes in multiple places doesn't guarantee there's duplicates, but there very well could be some paths we missed.

```
4s ▶ helm template insights-agent fairwinds-stable/insights-agent --values values.yaml --version 2.18.2 | kubectl slice -f - -o /tmp
Wrote /tmp/serviceaccount-insights-agent-cronjob-executor.yaml -- 183 bytes.
Wrote /tmp/serviceaccount-insights-agent-kube-bench.yaml -- 182 bytes.
Wrote /tmp/serviceaccount-insights-agent-workloads.yaml -- 169 bytes.
Wrote /tmp/secret-insights-agent-token.yaml -- 142 bytes.
Wrote /tmp/configmap-insights-agent-configmap.yaml -- 211 bytes.
Wrote /tmp/configmap-insights-agent-values.yaml -- 89319 bytes.
Wrote /tmp/clusterrole-insights-agent-workloads.yaml -- 296 bytes.
Wrote /tmp/clusterrolebinding-insights-agent-workloads.yaml -- 392 bytes.
Wrote /tmp/clusterrolebinding-insights-agent-workloads-view.yaml -- 377 bytes.
Wrote /tmp/role-insights-agent-cronjob-executor.yaml -- 424 bytes.
Wrote /tmp/role-insights-agent-get-logs.yaml -- 299 bytes.
Wrote /tmp/rolebinding-insights-agent-cronjob-executor.yaml -- 400 bytes.
Wrote /tmp/rolebinding-insights-agent-get-logs.yaml -- 522 bytes.
Wrote /tmp/job-insights-agent-install-reporter.yaml -- 1777 bytes.
Wrote /tmp/cronjob-kube-bench.yaml -- 4682 bytes.
Wrote /tmp/cronjob-workloads.yaml -- 3166 bytes.
Wrote /tmp/job-cronjob-executor.yaml -- 5020 bytes.
17 files generated.
```
(exits with no errors)

Values file

```
insights:
  organization: foo
  base64token: foo
  cluster: foo
kube-bench:
  enabled: true
  ```

**Comment by sudermanjr** [comment]
Please feel free to re-open if we can figure out how to reproduce this.
