### ISSUE TITLE
Helm Chart Update failed (vpa: 2.0.0)

### ISSUE THREAD

**Issue by sklohe** [reactiveops/charts#1221]
### What happened?

Tonight an update of the vpa helm-chart arrived via renovatebot. There seems to be a check for the necessary Kubernetes version, which unfortunately fails

Used k8s Versions:
v1.25.9-eks-0a21954 & v1.25.7-rc1+k3s1

Used helm-Version:
{v3.11.2", GitCommit:"912ebc1cd10d38d340f048efaf0abda047c3468e", GitTreeState:"clean", GoVersion:"go1.18.10"}

Helm Error Messages:
1.) Error: UPGRADE FAILED: chart requires kubeVersion: >= 1.21.0 which is incompatible with Kubernetes v1.25.9-eks-0a21954
2.) Helm upgrade failed: chart requires kubeVersion: >= 1.21.0 which is incompatible with Kubernetes v1.25.7-rc1+k3s1

### What did you expect to happen?

The check for the kubernetes version used should not fail

### How can we reproduce this?

Do a helm chart upgrade with the newest vpa Version 

### Version

vpa - 2.0.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment]
Seems like we need to update the kubeVersion to allow pre-releases. PR opened.
