### ISSUE TITLE
[stable/rbac-manager] - OKD/Openshift 4 errors

### ISSUE THREAD

**Issue by jjmichaud** [reactiveops/charts#1228]
### What happened?

When running the rbac-manager on OKD/Openshift 4.10, the following error shows up in the logs when it tries to create new RoleBindings

```
cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on
```

### What did you expect to happen?

That the rbac-manager creates the rolebindings as expected

### How can we reproduce this?

Based on other research ( see https://github.com/crossplane/crossplane/issues/3443#issuecomment-1313760019 ) it looks like this happens on OKD/Openshift because it enables the plug-in [OwnerReferencesPermissionEnforcement](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement)

I think this means if you enabled the OwnerReferencesPermissionEnforcement plugin on a k8s cluster it would have the same error that is happening on OKD/Openshift

...however I already believe there is a solution (see additional context) which would just need to be confirmed there is no regression for non OKD/Openshift installs.

### Version

Helm Chart 1.17.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Based on my research it appears this same problem has come up in the main code

- https://github.com/FairwindsOps/rbac-manager/issues/180

They offer a solution by adding the following to the ClusterRole
```
  - apiGroups:
      - rbacmanager.reactiveops.io
    resources:
      - rbacdefinitions/finalizers
    verbs:
      - "*"
```
There is even a comment at the end suggesting this should be fixed in the Helm chart too.

I can also confirm that with the additional permissions to the clusterrole, rbac-manager works as expected on OKD/Openshift.

**Comment by sudermanjr** [comment]
Thanks for the detailed info - I opened a fix PR on the chart.
