### ISSUE TITLE
[stable/vpa] Expose ability to add deployment annotations in the vertical pod autoscaler helm chart

### ISSUE THREAD

**Issue by fullykubed** [reactiveops/charts#1293]
**Is your feature request related to a problem? Please describe.**
Cannot add annotations to the deployments of the helm chart for the vertical pod autoscaler. Hinders our ability to use projects like the [reloader](https://github.com/stakater/Reloader) which in our case we need in order to restart the VPA pods to pick up new webhook certs managed by cert-manager.

**Describe the solution you'd like**
Provide the ability to add annotations to the deployments similar to the other resources.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by sudermanjr** [comment]
This would be great. Would you be willing to contribute this?
