### ISSUE TITLE
[stable/polaris] Support `string` type of `config` value

### ISSUE THREAD

**Issue by mikutas** [reactiveops/charts#1303]
**Is your feature request related to a problem? Please describe.**

Current readme says that `config` value's type is `string`, but it's `map` in fact.
If `config` value's type is really `string`, we can use helm's `set-file` option and keep config file DRY.

**Describe the solution you'd like**

For backward compatibility, we still support `map` type of `config` value and render that as ever.
But on the other hand we also accept `string` type of `config` value and render that properly.

**Describe alternatives you've considered**
no idea

**Additional context**
none

**Comment by rbren** [comment]
> we can use helm's set-file option and keep config file DRY.

Can you say more about this use case? I'm not sure I understand

**Comment by rbren** [comment]
Thought about it more--my guess is that you want to keep your Polaris config in a separate file (without the top-level `config` key that would make it a valid Helm values.yaml file), and reuse that with both helm and the polaris binary. Is that right?

**Comment by mikutas** [comment]
Yes, first our org began to use Polaris CLI in CI and created our own config file.
After a while, we decided to deploy admission webhook using helm chart, and wanted to reuse the config.

**Comment by sudermanjr** [comment]
I think the proposed implementation in https://github.com/FairwindsOps/charts/pull/1304 should be fine. Robert will be back next week and we can get it approved once it's rebased and moved out of draft.
