### ISSUE TITLE
Security Issue: ClusterRoleBinding is using a pre-defined role which fails security scans and blocks deployment

### ISSUE THREAD

**Issue by ghost** [reactiveops/charts#1321]
### What happened?

I'm trying to deploy Polaris to our cluster using Helm, but it fails the [snyk](https://snyk.io/) security scan with the following security error:

```
Issues
High Severity Issues: 1
  [High] RoleBinding or ClusterRoleBinding is using a pre-defined role
  Info:    A RoleBinding or ClusterRoleBinding was found using one of the
           default user facing roles, `cluster-admin`, `admin`, `edit` or
           `view`. Using a default user facing role may be overly permissive.
           For a ClusterRoleBinding this would be considered high severity.
  Rule:    https://snyk.io/security-rules/SNYK-CC-K8S-46
  Path:    [DocId: 1] > roleRef > name
  File:    polaris/templates/rbac.yaml
  Resolve: Update roleRef.name to a specific role name with only the necessary
           permissions
```

I'd like to create a specific role rather than use the [generic 'view' default role as it does in the template](https://github.com/FairwindsOps/charts/blob/1c73eb95d10a8d5610972ad0535ad0058f684be3/stable/polaris/templates/rbac.yaml#L8). 

```
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
```

Does anyone know what the necessary RBAC / CRD permissions are for Polaris in a cluster?

### What did you expect to happen?

The scan to be successful (Polaris follows security best practices) and for it to pass our deployment pipeline.

### How can we reproduce this?

Run a [snyk](https://snyk.io/) security scan on the Polaris helm chart

### Version

name: polaris version: 5.14.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment]
Polaris rbac is dependent on the policies that you specify. If a more fine-grained permission is desired, it will likely need to be custom to the specific use-case. We can look at updating the chart to use a dedicated clsuterrole, however it will likely be very similar to the built-in `view` role. If all policies are enabled, Polaris as an auditing tool needs permissions to view a large number of resources in the cluster, across all namespaces

**Comment by rbren** [comment]
@standoubtayx we need to attach to `view` in order to see all resources that you might want to run checks against. You can disable this by setting `rbac.enabled=false` and creating your own role/binding
