### ISSUE TITLE
Goldilocks VPA Grafana Dashboard

### ISSUE THREAD

**Issue by kaiohenricunha** [reactiveops/charts#1372]
**Is your feature request related to a problem? Please describe.**

I know Goldilocks provides its own dashboard, but the thing is most projects will prefer concentrating panels and views on Grafana.

**Describe the solution you'd like**

A Grafana dashboard that leverages the metrics exposed by the VPA recommender and updater, preferably bundled with the goldilocks installation.

It should mainly, and ideally, **clearly** show Current Usage vs Recommended Usage, among some other panels and details

**Describe alternatives you've considered**

I have been using this dashboard:
https://grafana.com/grafana/dashboards/14588-vpa-recommendations/

While it is pretty good, I don't think it makes the best use of the rich metrics exposed by the VPA recommender, updater, and kube state metrics.

**Additional context**

**Comment by sudermanjr** [comment]
Since we're not heavy Grafana users, I don't see this being something we work on, but I would be happy to support a community contribution for it.
