### ISSUE TITLE
rbac-manager 1.8.0 was released

### ISSUE THREAD

**Issue by madddi** [reactiveops/charts#1457]
Hi,

rbac-manager 1.8 was released some time ago: https://github.com/FairwindsOps/rbac-manager/releases/tag/v1.8.0

Is there a reason why it wasn't updated in the helm chart?

**Comment by sudermanjr** [comment]
No particular reason, probably just wasn't a priority. Would you be willing to open a PR to bump that up?

**Comment by ryanisfluffy** [comment]
Addressed in #1479
