### ISSUE TITLE
Unnecessary helm hooks

### ISSUE THREAD

**Issue by bianchi2** [reactiveops/charts#1507]
### What happened?

Is there a reason why https://github.com/FairwindsOps/charts/blob/master/stable/vpa/templates/webhooks/jobs/certgen-clusterrole.yaml#L7 have both pre and post install/upgrade hooks? The jobs themselves https://github.com/FairwindsOps/charts/blob/master/stable/vpa/templates/webhooks/jobs/certgen-create.yaml#L7 have only pre-install/upgrade

Having both pre and post install hooks makes argo stuck in Syncing forever.

### What did you expect to happen?

job templates having just pre-install, pre-upgrade hooks

### How can we reproduce this?

Deploy vpa helm chart with ArgoCD.

### Version

latest

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment]
I thought the post install is there to remove the RBAC bindings used for the pre-install hook in order to de-escalate privileges needed.

**Comment by sudermanjr** [comment]
Looking closer, I see what you're saying. That's odd. Do you want to open a PR to remove them?
