### ISSUE TITLE
Allow definition of multiple recommenders

### ISSUE THREAD

**Issue by thejuan** [reactiveops/charts#1528]
Apologies if this is already possible, it isn't clear to me how.

[VPA allows defining multiple recommenders configured for different scenarios](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/README.md#starting-multiple-recommenders)

It would be good if the chart also allowed the specification of multiple recommenders

**Comment by sudermanjr** [comment]
This is not possible, but would be a very cool addition. Thanks for the suggestion!
