### ISSUE TITLE
[insights-agent] re-use cron schedule instead of creating a new one

### ISSUE THREAD

**Issue by ejether** [reactiveops/charts#656]
When using an "upgrade when there is a difference" approach to installing the insights agents, the on the fly generated schedules will _always_ show as a difference and therefore in will repeatedly re-upgrade the release even when there are no _other_ changes. 

I'd rate this as a "nice to have" for sure but I'd prefer it if subsequent `helm diff` could re-use the schedule it generated or, programmatically generate the _same_ schedule so there would be no diff on subsequent upgrades here https://github.com/FairwindsOps/charts/blob/master/stable/insights-agent/templates/_specs.yaml#L24

I see that one can set the schedule for the individual plugins so the obvious work around is to declare a schedule for each but _wouldn't it be cool if_ that wasn't necessary?  :D 

Implementation wise, `helm`, as far as I know, doesn't really let you do that natively so generating the cron schedule base on  some sort of "hashing" of the `release name + plugin name % 60` or something silly like that. There is probably a better solution but that would be a very transparent one.

**Comment by rbren** [comment]
ooh neat idea!
