### ISSUE TITLE
[rbac-manager] Add RBACDefinitions Options to chart

### ISSUE THREAD

**Issue by eyenx** [reactiveops/charts#693]
**Is your feature request related to a problem? Please describe.**

As of today we are deploying rbac-manager on a few Clusters with ArgoCD. After deploying rbac-manager we still need to deploy rbac-definitions to the cluster separately. We usually end up using Raw Yamls inside a separate folder or repo.

**Describe the solution you'd like**

We would appreciate to have the ability to deploy rbac-definitions together with this Chart in one go. 

**Describe alternatives you've considered**

We have considered creating our own Chart just for deploying rbac-definitions.

**Additional context**

https://github.com/adfinis-sygroup/helm-charts/issues/131

**Comment by sudermanjr** [comment]
So, we used to have this option in the chart, a major version or two ago. There was some issue with managing it that caused us to remove it.

It may have been a helm 2 thing, I'm not sure. Maybe @lucasreed remembers?

**Comment by lucasreed** [comment]
Unfortunately I don't remember. I think it's outside the scope here as it's already a bit of a pain to manage CRD's themselves. It's generally not done in most controller installs where there is a CRD. That's up to the implementer to install afterwards (thinking along the lines of cert-manager among others).

I'm going to close this as wontfix.

**Comment by eyenx** [comment]
Thanks.

We created a chart in our own repos. 

https://github.com/adfinis-sygroup/helm-charts/tree/master/charts/rbac-definitions
