### ISSUE TITLE
[vpa] add podLabels to VPA chart

### ISSUE THREAD

**Issue by francRang** [reactiveops/charts#712]
**Is your feature request related to a problem? Please describe.**
Need a way to add custom labels to the pods

**Describe the solution you'd like**
Add podLabels to values.yaml

**Describe alternatives you've considered**
N/A

**Additional context**
Need a way to set custom labels on pods through Helm chart

**Comment by sudermanjr** [comment]
Should be fairly easy to implement.

Should we do podLabels for each individual component separately, or shared pod labels, or both?
