### ISSUE TITLE
Update helm chart to get rbac-manager v1.1.1 (released on 25 Feb 2022)

### ISSUE THREAD

**Issue by lyssar** [reactiveops/charts#738]
At the moment you will get the rbac-manager version from september instead the new released v1.1.1
please consider update :) thnx alot

**Comment by sudermanjr** [comment]
@lyssar Happy to do that. Opened a PR for it myself since it was a straightforward fix.

**Comment by lyssar** [comment]
Thank you very much :) that was a quick one!
