### ISSUE TITLE
[rbac-manager] prevent CRD removal on uninstall unless explicitly enabled

### ISSUE THREAD

**Issue by MaxRink** [reactiveops/charts#882]
**Is your feature request related to a problem? Please describe.**
Currently the chart uses templates and not the helm3 CRD folder to manage its CRDs.
This causes issues in helm delete, as all of the CRDs get purged
**Describe the solution you'd like**
either move the CRDs to helm3 CRD folder or mark them as "skipped" for helm delete, add a seperate hookm to actually delete them if explicitly enabled

**Comment by sudermanjr** [comment]
I think we should move to the helm3 CRD folder, but I'm uncertain about the implications of a breaking change to the chart like that. I'll have to solicit some feedback from folks.
