### ISSUE TITLE
[stable/vpa] "targetRef" field dropped in "VerticalPodAutoscaler" definition

### ISSUE THREAD

**Issue by wesleyhaws** [reactiveops/charts#919]
### What happened?

The "targetRef" field is completely ignored in the "VerticalPodAutoscaler" with resources using the "autoscaling.k8s.io/v1" api on version 1.0.0 (0.9.2 VPA) helm chart. 

I need to use this version as 0.10.0 of VPA only support 1.22+ of kubernetes and I'm currently using a version below that and it won't be easy to upgrade. 

Here is my definition:
```
{{- range $app := .Values.vpas }}
---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: "recommendations-{{ $app.name }}"
  namespace: "{{ $app.namespace }}"
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ $app.name }}
  updatePolicy:
    updateMode: "{{ default "Off" $app.updateMode }}"
  resourcePolicy:
    containerPolicies:
      - containerName: "{{ default "*" $app.containerName }}"
        controlledResources:
          - cpu
          - memory
        mode: "Off"
{{- end }}
```
Here is what the `-o yaml` looks like of the resource:
```
...
...
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources:
      - cpu
      - memory
      mode: "Off"
  targetRef: {}
  updatePolicy:
    updateMode: "Off"
```
According to `helm template` and the `kubectl.kubernetes.io/last-applied-configuration` annotation I see that `targetRef` is there with the correct values, it's just dropped prior to applying for some reason.

### What did you expect to happen?

When I deployed it I expected the targetRef fields to be populated.

### How can we reproduce this?

Download the helm release add the above vpa defintion with any values you want. Then change the `updater` to `false` in your variables file. 

### Version

fairwinds-stable/vpa --version 1.0.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Am I missing anything?

I have checked the `vpa-v1-crd.yaml` file and it does include a definition for `targetRef` so something else must be going on I don't know about.

**Comment by sudermanjr** [comment]
I don't seem to be able to reproduce this issue:

```
▶ helm install vpa fairwinds-stable/vpa --version v1.0.0 --namespace vpa --set updater.enabled=false --create-namespace

▶ k apply -f vpa.yaml

▶ k -n vpa get vpa test-vpa -oyaml
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"autoscaling.k8s.io/v1beta2","kind":"VerticalPodAutoscaler","metadata":{"annotations":{},"name":"test-vpa","namespace":"vpa"},"spec":{"targetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"vpa-recommender"},"updatePolicy":{"updateMode":"Off"}}}
  creationTimestamp: "2022-08-22T21:47:22Z"
  generation: 1
  name: test-vpa
  namespace: vpa
  resourceVersion: "71708"
  uid: 43b15414-0f49-4958-9c37-65f8379f105b
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vpa-recommender
  updatePolicy:
    updateMode: "Off"
```

vpa.yaml
```yaml
---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: "test-vpa"
  namespace: vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: vpa-recommender
  updatePolicy:
    updateMode: "Off"
```

**Comment by sudermanjr** [comment]
Also, in your original yaml, you specify `autoscaling.k8s.io/v1beta2`, but in the issue state you need `autoscaling.k8s.io/v1`, so I'm a bit confused

**Comment by wesleyhaws** [comment]
Yes, I was able to solve it late yesterday. User error.

It was because I was deploying with helm but had made an update to the CRD
and never redeployed the CRD. So the vpa was referencing the old CRD. The
old CRD didn't have the targetRef definition.

**Comment by sudermanjr** [comment]
Awesome, glad you got it worked out!
