### ISSUE TITLE
Dont use CPU limits

### ISSUE THREAD

**Issue by MaxRink** [reactiveops/charts#931]
**Is your feature request related to a problem? Please describe.**
Currently soe charts like rbac-manager use cpu limits.
You should propably not specify them by default.
https://home.robusta.dev/blog/stop-using-cpu-limits/

**Describe the solution you'd like**
Drop the default cpu limits

**Comment by sudermanjr** [comment]
The option to remove limits exists in the charts, please feel free to use that option at your discretion.

**Comment by ghost** [comment]
I tried searching for a specific option to remove CPU limits, but couldn't find one.

If I configure the values.yml file for the vpa helm chart like this, without a CPU limit:

```
vpa:
  recommender:
    resources:
      limits:
        memory: 500Mi
```
Then running `helm template` will still output a file with a CPU limit of `200m`, based on the default values.

I'd like to avoid needing patching the templated file.
